import discord

options = [
        discord.SelectOption(label='Missiz Frizz', value='Missiz Frizz'),
        discord.SelectOption(label='Sylargh', value='Sylargh'),
        discord.SelectOption(label='Klime', value='Klime'),
        discord.SelectOption(label='Nileza', value='Nileza'),
        discord.SelectOption(label='Comte Harebourg', value='Comte Harebourg'),
        discord.SelectOption(label='Harebourg et Frizz', value='Harebourg et Frizz'),
        discord.SelectOption(label='Harebourg et Sylargh', value='Harebourg et Sylargh'),
        discord.SelectOption(label='Harebourg et Klime', value='Harebourg et Klime'),
        discord.SelectOption(label='Harebourg et Nileza', value='Harebourg et Nileza'),
        discord.SelectOption(label='Merkator', value='Merkator'),
        discord.SelectOption(label='Nidas', value='Nidas'),
        discord.SelectOption(label='Reine des Voleurs', value='Reine des Voleurs'),
        discord.SelectOption(label='Protozorreur', value='Protozorreur'),
        discord.SelectOption(label='Vortex', value='Vortex'),
        discord.SelectOption(label='Chaloeil', value='Chaloeil'),
        discord.SelectOption(label='Capitaine Meno', value='Capitaine Meno'),
        discord.SelectOption(label='Koutoulou', value='Koutoulou'),
        discord.SelectOption(label='Dantinea', value='Dantinea'),
        discord.SelectOption(label='Tal Kasha', value='Tal Kasha'),
        discord.SelectOption(label='Anerice', value='Anerice'),
        discord.SelectOption(label='Ilyzaelle', value='Ilyzaelle'),
        discord.SelectOption(label='Solar', value='Solar'),
        discord.SelectOption(label='Bethel', value='Bethel'),
        discord.SelectOption(label='Dazak Martegel', value='Dazak Martegel'),
        discord.SelectOption(label='Torkelonia', value='Torkelonia'),
        discord.SelectOption(label='Corruption', value='Corruption'),
        discord.SelectOption(label='Guerre', value='Guerre'),
        discord.SelectOption(label='Servitude', value='Servitude'),
        discord.SelectOption(label='Misere', value='Misere'),
        discord.SelectOption(label='Cavaliers de l Eliocalypse', value='Cavaliers de l Eliocalypse'),
        discord.SelectOption(label='Roi Imagami', value='Roi Imagami'),
        discord.SelectOption(label='Reine Amirukam', value='Reine Amirukam'),
        discord.SelectOption(label='Kabahal', value='Kabahal'),
        discord.SelectOption(label='L eternel Conflit', value='L eternel Conflit'),
        discord.SelectOption(label='Belladone', value='Belladone'),
    ]